### ISSUE TITLE
enctype is frozen to application/x-www-form-url-encoded

### ISSUE THREAD

**Issue by ahmed-masud** [expandjs/xp-form#1]
The element does not pick up changes to `enctype` either programmatically or through the `enctype='foo/bar'`. so for example

``` html
<form is='xp-form' enctype='application/json' id='myform'>
</form>
```

and then later

``` html
<script>
   var foo = document.querySelector('#myform');
   foo.enctype = 'application/json';
   console.log(foo)
   // outputs application/x-www-form-urlencoded
</script>   
```

There seems to be a conflict in the order of mutation handling through XP.onMutation and reflectToAttribute.  I could not trace it down. Hopefully this can be fixed.

The current work around that I'm using is to simply access `xpFormRequest` and update the `enctype` in there.

**Comment by Pupix** [comment]
This happens because `application/json` is **not a valid form enctype**. The form is just defaulting to `application/x-www-form-urlencoded` because the enctype is invalid. If you use `multipart/form-data` or `text/plain` it works just fine.

This just shows that we may need to add a custom property which sets the _enctype_ on `xpFormRequest` without using the native `enctype` as it's very limited.

**Comment by Pupix** [comment]
Now there's a new property called `contentType` (attribute is `content-type`) which lets you set the format of the data to be submitted. **enctype is deprecated**

Clean bower cache and reinstall `xp-form`.

Cheers!

**Comment by ahmed-masud** [comment]
Great ... thank you!
